name: Check if User is registered at jobsimulator.dev

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Set up environment variables
      env:
        URL: ${{secrets.URL}}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        USER_EMAIL: ${{ github.event.sender.email }}
      run: |
        echo "SECRET_KEY=${SECRET_KEY}" >> $GITHUB_ENV
        echo "USER_EMAIL=${USER_EMAIL}" >> $GITHUB_ENV
    - name: Call serverless endpoint
      run: |
        curl -X POST -H "key: ${SECRET_KEY}" -d "${USER_EMAIL}" "${URL}"
